# Este archivo configura un workflow de GitHub Actions para proyectos que usan Deno.

name: Deno # Nombre del workflow

on: # Define los eventos que activan este workflow
  push: # Se ejecuta cuando hay un push a la rama principal
    branches: ["main"]
  pull_request: # Se ejecuta cuando se crea o actualiza un pull request hacia la rama principal
    branches: ["main"]

permissions: # Define los permisos para este workflow
  contents: read # Permite leer el contenido del repositorio

jobs: # Define los trabajos que se ejecutarán en este workflow
  test: # Nombre del trabajo
    runs-on: ubuntu-latest # El trabajo se ejecutará en un contenedor con Ubuntu

    steps: # Pasos que se ejecutarán en este trabajo
      - name: Checkout repository # Paso para clonar el repositorio
        uses: actions/checkout@v4 # Acción oficial de GitHub para clonar el repositorio

      - name: Setup Deno # Paso para instalar Deno
        uses: denoland/setup-deno@v1.1.2 # Acción oficial para configurar Deno
        with:
          deno-version: v1.x # Instala la última versión estable de Deno

      - name: Verify formatting # Paso para verificar el formato del código
        run: deno fmt --check # Comprueba si el código está formateado correctamente

      - name: Run linter # Paso para ejecutar el linter
        run: deno lint # Analiza el código en busca de problemas de estilo o errores

      # Paso opcional: Ejecutar pruebas solo si existen
      - name: Run tests (optional) # Paso para ejecutar pruebas si existen
        run: |
          if deno test --allow-all; then
            echo "Tests passed.";
          else
            echo "No tests found or tests failed.";
          fi
